name: CI
run-name: ${{ github.event.inputs.name }}

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

  # Manual trigger for release
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name'
        required: true
        default: 'snapshot'
      text:
        description: 'Release description'
        required: true
        default: 'Snapshot release of the main branch'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2

      - run: opam install . --deps-only --with-test
          
      - name: Tests
        run: |
          opam exec -- make test
      
      - name: Build executable
        run: |
          opam exec -- make install INSTALL_ROOT=.

      - name: Release
        # Only if manually triggered
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.name }}
          tag_name: ${{ github.event.inputs.name }}
          target_commitish: main
          body: ${{ github.event.inputs.text }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            hashette
